name: my_project
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.8.1 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1 # Or the latest version

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
